use_frameworks!

platform :ios, '10.0'

target 'JFHeroBrowser_Example' do
  pod 'JFHeroBrowser', :path => '../../'
  pod 'Kingfisher', '6.3.1'
  pod 'JFPopup', '1.4.2'
  pod 'SDWebImage'
  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGN_IDENTITY'] = ''
           end
      end
    end
  end

  target 'JFHeroBrowser_Tests' do
    inherit! :search_paths

    
  end
end
